#!/bin/bash
#
# on the walrus gnms machine, this and other files are sourced according 
# to the following hierarchy
#
# .bash_profile
#   |-- .bashrc
#   `-- .bash_user
#     `-- .df/mainly        CURR FILE
#         |-- .df/bash_user_dev.env
#         |-- .df/aliases.sh
#         |-- .df/functions.sh
#         `-- .df/variables.sh
#

fSourceIfThere(){
	local fileToSource="${1}"

	if [[ -f "${fileToSource}" ]] ; then
		echo "${fileToSource}"
		source "${fileToSource}"
	else
		echo "NO ${fileToSource}!"
	fi
}



# (fix due to gnms .bash_user_dev) BACKUP ps1
myPS1=$PS1

# original located at /usr/mgr/env/anp_cc/bash_user_dev.env
#source ~/.dotfiles/bash_user_dev.env
fSourceIfThere ~/.dotfiles/bash_user_dev.env

# (fix due to gnms .bash_user_dev) RESTORE ps1
export PS1=$myPS1

# (fix due to gnms .bash_user_dev) reset shell option
set -o emacs

# (fix due to gnms .bash_profile)
# make backspace not output ^? in vi when remotely connected (via PuTTy)
/bin/stty erase \^?


#
# makes anything defined automatically exported
set -o allexport
#


if [[ "$(hostname)" = "walrus" ]] ; then
#############################################
# CLEARCASE SETUP SHTUFF
#############################################
#_FCR_SETUP_VALUE=6349
export _FCR_SETUP_VALUE=`~/bin/bdaviesCurrCr.sh`
#_FCR_SETUP_VALUE=6371
#_FCR_SETUP_VALUE=6474

#fcr_setup $_FCR_SETUP_VALUE
# ACTIVATES VIEW:::
fcr $_FCR_SETUP_VALUE


##
# in order to dev or setup a view for your curr CR, execute these two lines FIRST
#  $ nn
#  $ . .b
echo 'say [nn][. .b]';
#
alias nn='newgrp anp_cc'
#
BDAVIES_CURR_CR="$HOME/bin/bdaviesCurrCr.sh"
echo "[$BDAVIES_CURR_CR]: $($BDAVIES_CURR_CR)"
echo "to set view: fcr CRNUMBER"
##
#############################################
# /CLEARCASE SETUP SHTUFF
#############################################
fi


## smbclient -L bdavies522276
# smbmount

fSourceIfThere ~/.dotfiles/aliases.sh
fSourceIfThere ~/.dotfiles/functions.sh
fSourceIfThere ~/.dotfiles/variables.sh

